let fn = () => {
    try{
    console.log("Hello");
    }catch(err){
        console.log(err);
    }
    finally{
        console.log("I will run");
        // return 10;
    }
}

// let reVal = fn();
// console.log(reVal);
